name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx (for better builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push image
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your-dockerhub-username/your-app-name:latest
